# Generated by Django 5.1 on 2024-11-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='image_name',
            field=models.CharField(default='image-name', max_length=100),
        ),
    ]
