# Generated by Django 5.1 on 2024-11-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_mobiles_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobiles',
            name='image_name',
        ),
        migrations.AddField(
            model_name='mobiles',
            name='image_url',
            field=models.CharField(default='image-name', max_length=300),
        ),
    ]
